In [3]:
import numpy as np

In [4]:
def to_binary(num):
    temp = []
    while(num):
        temp.append(num%2)
        num = int(num/2)
    return temp[::-1]
#to_binary(987) #binary of 987 = 1111011011

**Getting input vectors**

In [5]:
x=[]
for item in '0123456789':
    ascii_value = ord(item)
    x.append(to_binary(ascii_value))
    
x = np.array(x)
x

array([[1, 1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 1],
       [1, 1, 0, 0, 1, 0],
       [1, 1, 0, 0, 1, 1],
       [1, 1, 0, 1, 0, 0],
       [1, 1, 0, 1, 0, 1],
       [1, 1, 0, 1, 1, 0],
       [1, 1, 0, 1, 1, 1],
       [1, 1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0, 1]])

**Output Vector**

In [6]:
t = (1,-1,1,-1,1,-1,1,-1,1,-1)
t

(1, -1, 1, -1, 1, -1, 1, -1, 1, -1)

**Weight Vector**

In [7]:
wts = np.ones(6)
wts

array([1., 1., 1., 1., 1., 1.])

**Theta and Alpha (learning rate)**

In [8]:
theta = 0.2
lr = 1

**Activation Function**

In [9]:
def calcY(y):
    if y>=theta:return 1
    else: return -1

**Weight Update Function**

In [10]:
def weight_update(w,t,x):
    for i in range(6):
        w[i] = w[i] + (lr * t * x[i])
    #print(w)

**Model Building**

In [11]:
epoch = 0

while(epoch != 10):
    for i in range(10):
        Y_in = 0
        
        for j in range(6):
            Y_in = Y_in + x[i][j] * wts[j]
            
        Y_calc = calcY(Y_in)

        if Y_calc != t[i]:
            weight_update(wts,t[i],x[i])
        else:
            pass
    epoch += 1

**Printing Final Weights**

In [12]:
print(wts)

[ 1.  1.  1.  1.  0. -4.]


**Test cases**

In [13]:
def evenOdd(x):
    temp = to_binary(ord(x))
    y_in = 0
    for i in range(6):
        y_in += temp[i] * wts[i]
    
    if(calcY(y_in) == 1):
        print("even")
        return
    else:
        print("odd")

In [14]:
evenOdd('3')

odd


In [15]:
evenOdd('6')

even


In [16]:
evenOdd('9')

odd
