In [1]:
x1 = [[1,1, 1, 1]];
x2 = [[1,-1,-1, 1]];
x3 = [[-1,1,-1,-1]];
x4 = [[1,-1,-1,-1]];

In [2]:
import numpy as np
# Transpose
x11 = np.transpose(x1, axes = None)
print(x11)
w1 = x1*x11
print(w1)
x21 = np.transpose(x2, axes = None)
print(x21)
w2 = x2*x21
print(w2)
x31 = np.transpose(x3, axes = None)
print(x31)
w3 = x3*x31
print(w3)
x41 = np.transpose(x4, axes = None)
print(x41)
w4 = x4*x41
print(w4)

[[1]
 [1]
 [1]
 [1]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[ 1]
 [-1]
 [-1]
 [ 1]]
[[ 1 -1 -1  1]
 [-1  1  1 -1]
 [-1  1  1 -1]
 [ 1 -1 -1  1]]
[[-1]
 [ 1]
 [-1]
 [-1]]
[[ 1 -1  1  1]
 [-1  1 -1 -1]
 [ 1 -1  1  1]
 [ 1 -1  1  1]]
[[ 1]
 [-1]
 [-1]
 [-1]]
[[ 1 -1 -1 -1]
 [-1  1  1  1]
 [-1  1  1  1]
 [-1  1  1  1]]


In [3]:
W = w1+w2+w3+w4
print(W)

[[ 4 -2  0  2]
 [-2  4  2  0]
 [ 0  2  4  2]
 [ 2  0  2  4]]


In [4]:
np.dot(x1,W)

array([[4, 4, 8, 8]])

In [5]:
def make_diagonal_zero(matrix):
    for i in range(min(len(matrix), len(matrix[0]))):
        matrix[i][i] = 0
    return matrix

In [6]:
W_rev = make_diagonal_zero(W)
print(W_rev)

[[ 0 -2  0  2]
 [-2  0  2  0]
 [ 0  2  0  2]
 [ 2  0  2  0]]


In [7]:
print(W)

[[ 0 -2  0  2]
 [-2  0  2  0]
 [ 0  2  0  2]
 [ 2  0  2  0]]


In [8]:
# testing of the Hopfield vectors
xt1 = np.dot(x1,W_rev)
print(xt1)

[[0 0 4 4]]


In [9]:
def activate(x, theta=0):
    return np.where(x>theta, 1, np.where(x == theta, x, 0))

In [10]:
xt1_act = activate(xt1)
print(xt1_act)

[[0 0 1 1]]


In [11]:
if(np.array_equal(x1, xt1_act)):
  print("testing complete")
else: print("testing failed")

testing failed
